### ISSUE TITLE
Nested resouces

### ISSUE THREAD

**Issue by andyw8** [tkadauke/motion-resource#10]
I have the following classes:

```
class Market < MotionResource::Base
  has_many :market_days
end

class MarketDay < MotionResource::Base
  belongs_to :market
  self.member_url = "markets/:market_id/market_days/:id"
end
```

And I'm trying to fetch a particular market_day through the market_days association:

```
market.market_days.find(day.date) do |market_day|
  ...
end
```

but this fails with:

```
undefined method `call' for "2013-06-16":String (NoMethodError)
  from find.rb:61:in `request_block_call:'
  from find.rb:18:in `block in fetch_member:'
  from requests.rb:69:in `block in http_call:'
  from query.rb:358:in `call_delegator_with_response'
```

("2013-06-16" is the ID of the date I'm trying to fetch).

Does motion-resource support this? Do I have the syntax wrong?

**Comment by tkadauke** [comment]
No, motion-resource doesn't support finding a single record through an association yet. However, I don't think it's a big issue, because you can always write

```
MarketDay.find(day.date, :market_id => market.id) do |market_day|
  …
end
```
