### ISSUE TITLE
Add custom headings to every request (e.g. auth_token)

### ISSUE THREAD

**Issue by ajbraus** [tkadauke/motion-resource#16]
Hi,

Is there a way to add default headers to requests? e.g.

  def self.headers
    {
      'Content-Type' => 'application/json',
      'Authorization' => "Token token=\"#{App::Persistence['authToken']}\""
    }
  end

**Comment by tkadauke** [comment]
Yes. Set the model's class variable default_url_options hash. In your case it should contain a key :headers with the headers hash above as a value.

See the options parameter of the initialize method here for a reference: https://github.com/rubymotion/BubbleWrap/blob/master/motion/http/query.rb

**Comment by joshsmith** [comment]
Is there any way we can do this globally, just like you can with `MotionResource::Base.root_url`?

**Comment by tkadauke** [comment]
Yes. Just use

``` ruby
MotionResource::Base.default_url_options = { :headers => { … } }
```

**Comment by joshsmith** [comment]
Thanks @tkadauke! :beer:
