### ISSUE TITLE
Logging actions

### ISSUE THREAD

**Issue by stefanvermaas** [tkadauke/motion-resource#17]
Hi @tkadauke 

I'm having problems using your gem. I've everything set up, just like the readme tells me:

``` ruby
class Client < MotionResource::Base

  MotionResource::Base.root_url = "http://localhost:3000/api/"

  # Include the MotionModel
  include MotionModel::Model
  include MotionModel::ArrayModelAdapter
  include MotionModel::Validatable

  # Define the attribute accessors
  attr_accessor :id
  attribute :name

  # Define the columns of this model
  columns name: :string

  # Validate the client model
  validate :name, presence: true

  # Define the URL's for this resource
  self.collection_url = "client"
  self.member_url = "client/:id"
end
```

But it seems there's no request send to the API. For your convenience my app_delegate.rb:

``` ruby
# app_delegate.rb
    @client = Client.create( name: 'Your awesome client' )
    p @client
```

Cheers!

**Comment by tkadauke** [comment]
Hi @stefanvermaas,

I don't think MotionResource plays nice with MotionModel at the moment. To verify this, please try removing the MotionModel includes from your model and see if a request is issued. Also, please note that all requests are asynchronous and need callback blocks. So in your case you'd use:

Client.create(name: "something") do |client|
  p client
end

**Comment by stefanvermaas** [comment]
Hmm you seem to be right. That's a pitty.. Any clue why this happens?

**Comment by tkadauke** [comment]
Yeah. That's because essential methods like save and create are defined by both MotionResource and MotionModel. In your case the MotionModel version wins because the include happens after inheriting methods from the base class.

Why would you need both MotionModel and MotionResource in one class anyways? If you want to sync to the cloud, you should do that with two different model classes.

**Comment by stefanvermaas** [comment]
That's because I want to save the new instance locally and in the cloud at the same time. That's why I want to use MotionModel and MotionResource in the same class. 

Thereby I want to use the validation stuff of MotionModel, because I want to do client-side validation too. This is because I want to save requests to the cloud.

**Comment by tkadauke** [comment]
If all you need is saving new models and never load them from the cloud, then I think it is a much better design to separate the two concerns:
- Make one class that immediately saves locally (no asynchronous processing or background indicators necessary). This one should be a MotionModel class.
- Then add another class that saves changed resources to the cloud in the background, possibly in bulk. Here, MotionResource might help, but it's possible that it won't be a good fit. In the latter case, you'd have to build your own thing.

If you just need client-side validations, then try including MotionModel::Validatable only.

Anything else is more involved. I know it's unfortunate that it is that way, but syncing data between the device and the cloud is inherently complex. There is no framework that I know of that removes that complexity. In particular, even if you could use both MotionModel and MotionResource in one class, how would that even work? I can see that adding a new model is fairly straightforward, but what is the authorative source when a model already exists? The device? The cloud? What if a model was changed both locally and in the cloud? How would you handle multiple devices syncing the same model across devices? How would you push changes to other devices? These are just some of the problems that arise in iCloud apps and for that matter in all cloud syncing systems.

**Comment by stefanvermaas** [comment]
Well if every action is saved to the cloud. The cloud will always be the authoritative source. 

Possibly you could send a notification from the cloud to every device ( not sure or this is possible ) just like with sockets in NodeJS. An other option is to run an background task every minute/5 minutes that checks for updates from the cloud. 

I think conflicting models ( read: an other user changes the model from an other device/web ) isn't a concern for our application. Lucky me.

What I want is that every interaction with a model is executed on the device and in the cloud. So if I create a new user, I want it to be on the device and to be send to the cloud ( async is ideal for this ). 

The problem I have with separating the cloud and local model, is that I have to maintain two models, in case they change. It's less DRY. 

I think combining the local saves and the cloud saves would be awesome, because it's DRY and sexy :)

**Comment by tkadauke** [comment]
If the cloud is the authorative source at all times, why would you store locally? Just use the cloud and nothing else.

Also, is there more to what the cloud does than storage? Because if not, you should check out Parse and one of the RubyMotion wrappers, like my MotionParse. It's very similar to MotionResource. Te difference is that with Parse, you don't have to worry one bit about the cloud. It's all automatic. However, that's only true for "dumb" storage of models.

**Comment by stefanvermaas** [comment]
Because when the connection is offline, you want to have some data on the device to work with. It's a kind of caching mechanism. This will make everything faster.

**Comment by tkadauke** [comment]
Sounds like what you want is iCloud. You should look into that.

Am 10.10.2013 um 11:41 schrieb Stefan Vermaas notifications@github.com:
