### ISSUE TITLE
Relationships not translating urls correctly.

### ISSUE THREAD

**Issue by j-mcnally** [tkadauke/motion-resource#21]
```
class User < MotionResource::Base
  attr_accessor :id
  attribute :full_name, :abbreviated_name, :avatar50, :avatar70, :points_this_week, :points_today, :total_points, :monthly_points
  has_many :hidukens

  self.collection_url = "users"
  self.member_url = "users/:id"

end
```

```
class Hiduken < MotionResource::Base
  attr_accessor :id
  attribute :user_id, :points, :multiplier
  belongs_to :user

  self.collection_url = "users/:user_id/hidukens"
  self.member_url = "users/:user_id/hidukens/:id"

end
```

```
def my_load_data
    User.find(app_delegate.user_id) do |my_user, response|
      if response.ok?
        my_user.hidukens do |h|
          puts h.inspect
        end
      end
    end

  end
```

Makes a call to my api

```
/api/v1/users/:user_id/hidukens.json"
```

instead of

```
/api/v1/users/5/hidukens.json"
```

**Comment by j-mcnally** [comment]
```
Hiduken.fetch_collection("users/#{app_delegate.user_id}/hidukens") do |h, response|
      puts h.inspect
    end
```

seems to be an ok work around. i like how this is more flexible from a url standpoint but it would be nice to see railsy / AR relationships get better support.

Also the ability to specify the collection and member urls as part of the relationship would be nice, since you may have different urls for accessing data through different objects. I couldnt quite understand how this works now in code, so perhaps this is just a documentation issue. either way the serializaiton / parsing is amazing thank you!

**Comment by tkadauke** [comment]
Hey,

Try changing the `has_many :hidukens` in class `User` to the following:

```
has_many :hidukens, :params => { |r| { :user_id => r.id } }
```

This will auto-fill the `:user_id` parameter when you use the `hidukens` association from a `User` instance.

**Comment by j-mcnally** [comment]
thanks so much! as a side note ive forked a few projects and made them ruby-motion compatible, so im trying to give back as often as i ask for help :) thanks!

**Comment by aijkoopmans** [comment]
Hi, i've tried the solution
has_many :hidukens, :params => { |r| { :user_id => r.id } } 
but it's not the correct syntax and my app won't compile.

ruby version 2.2.1

**Comment by tkadauke** [comment]
Sorry, the correct syntax is

  has_many :hidukens, :params => lambda { |r| { :user_id => r.id } }
