### ISSUE TITLE
undefined method `class_attribute' for MotionResource::Base:Class

### ISSUE THREAD

**Issue by andyw8** [tkadauke/motion-resource#6]
I'm trying to add motion-resource to my project, but it fails at runtime with:

> **\* Terminating app due to uncaught exception 'NoMethodError', reason: 'undefined method `class_attribute' for MotionResource::Base:Class (NoMethodError)

Should it work with RubyMotion 2?

**Comment by andyw8** [comment]
I just noticed the warning from 'motion-support' to set `app.detect_dependencies = false`. That seems to have fixed it.

**Comment by tkadauke** [comment]
It should work. Are you using bundler? You need the latest version of motion-support in order to use motion-resource
